apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-test-pod
spec:
  containers:
    - name: test
      image: public.ecr.aws/docker/library/busybox:latest
      command:
        - sh
        - -c
        - "echo 'Amazon EBS storage is working' > /data/test.txt && sleep 3600"
      volumeMounts:
        - name: ebs-storage
          mountPath: /data

  volumes:
    - name: ebs-storage
      persistentVolumeClaim:
        claimName: ebs-test-pvc